### ISSUE TITLE
Parallelisation issue

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/CASA_eMERLIN_pipeline#83]
2017-11-13 02:48:30 | INFO | Deleted: emerge_2015.ms
2017-11-13 02:48:30 | INFO | Deleted: emerge_2015.ms.flagversions
2017-11-13 02:48:30 | INFO | Moved: emerge_2015_hanning.ms emerge_2015.ms
2017-11-13 02:48:30 | INFO | End hanning
2017-11-13 02:48:30 | INFO | Checking AOflagger version
2017-11-13 02:48:32 | INFO | AOflagger version is 2.9.0
2017-11-13 02:48:32 | INFO | Start ms2mms
2017-11-13 02:48:33     INFO    partition::utils::verify        Verifying arguments....Enum checking failed for separationaxis
2017-11-13 02:48:33     WARN    partition::utils::verify        Argument separationaxis failed to verify.
2017-11-13 02:48:33     SEVERE  partition::::@norma4.intra.astro.rug.nl:MPIClient       An error occurred running task partition.
2017-11-13 02:48:33     SEVERE  ms::close       Exception Reported: Table /scratch/users/radcliff/eMERLIN_pipeline/emerge_2015.mms does not exist
Traceback (most recent call last):
  File "/scratch/users/radcliff/eMERLIN_pipeline/casa-release-5.1.1-5.el7/lib/python2.7/init_welcome.py", line 24, in <module>
    execfile(__candidates[0])
  File "CASA_eMERLIN_pipeline/eMERLIN_CASA_pipeline.py", line 407, in <module>
    run_pipeline(inputs=inputs)
  File "CASA_eMERLIN_pipeline/eMERLIN_CASA_pipeline.py", line 138, in run_pipeline  
    em.ms2mms(vis=msfile,mode='parallel')
  File "CASA_eMERLIN_pipeline/functions/eMERLIN_CASA_functions.py", line 506, in ms2mms
    ms.writehistory(message='eMER_CASA_Pipeline: Converted MS to MMS for parallelisation',msname=vis[:-3]+'.mms')
  File "/scratch/users/radcliff/eMERLIN_pipeline/casa-release-5.1.1-5.el7/lib/python2.7/__casac__/ms.py", line 1127, in writehistory
    return _ms.ms_writehistory(self, *args, **kwargs)
RuntimeError: Table /scratch/users/radcliff/eMERLIN_pipeline/emerge_2015.mms does not exist
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
casa detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[18487,1],0]
  Exit code:    1
--------------------------------------------------------------------------

The inputs used that are on are run_importfits, summary_weblog, hanning and ms2mms. 

I have aoflagger 2.9.0. 

Small bug in the ms2mms function where separation axis should be set to 'auto' rather than '' 

I can change this directly in the master branch if that's ok with you @jmoldon ?

**Comment by jmoldon** [comment]
Sorry I updated that the other day to remove baseline, but I forgot to set auto, I assumed it was the default.

Yes, feel free to change it. If you push to master, remember to change the pipeline version in line 13 of eMERLIN_CASA_pipeline.py. Just increase the last number.

**Comment by jradcliffe5** [comment]
Ok great. this has been done. I will close the issue.
